- name: Basic Security Settings for Linux Hosts
  hosts: linux_hosts
  become: yes
  remote_user: tuxadm # Here insert your SSH connection user
  vars:
    ansible_ssh_pass: Pass_12345 # Here insert SSH user's password
    ansible_become_password: Pass_12345 # Here insert SSH sudoer user's password 
    zabbix_server_ip: 192.168.0.111 # Here insert your Zabbix server IP

  tasks:
    - name: Ensure UFW is installed
      apt:
        name: ufw
        state: present

    - name: Allow SSH through UFW
      ufw:
        rule: allow
        port: 22
        proto: tcp

    - name: Allow HTTP through UFW
      ufw:
        rule: allow
        port: 80
        proto: tcp

    - name: Allow HTTPS through UFW
      ufw:
        rule: allow
        port: 443
        proto: tcp

    - name: Allow Zabbix Server through UFW only from specific IP
      ufw:
        rule: allow
        port: 10051
        proto: tcp
        from_ip: "{{ zabbix_server_ip }}"

    - name: Enable UFW
      ufw:
        state: enabled

    - name: Ensure fail2ban is installed
      apt:
        name: fail2ban
        state: present

    - name: Configure fail2ban for SSH
      copy:
        dest: /etc/fail2ban/jail.local
        content: |
          [sshd]
          enabled = true
          port = 22
          logpath = /var/log/auth.log
          maxretry = 5

    - name: Ensure fail2ban is enabled and started
      systemd:
        name: fail2ban
        state: started
        enabled: yes

    - name: Ensure AppArmor is installed
      apt:
        name: apparmor
        state: present

    - name: Ensure AppArmor is enabled and started
      shell: |
        sudo systemctl enable apparmor
        sudo systemctl start apparmor
